### ISSUE TITLE
install pirate switch on demo.themeisle.com

### ISSUE THREAD

**Issue by dascalescuro** [Codeinwp/pirate-switch#22]
@selul can you please help us install pirate switch on these demos pages?

https://demo.themeisle.com/zerif-pro-app/
https://demo.themeisle.com/zerif-origin/
https://demo.themeisle.com/multiway-zerif/
https://demo.themeisle.com/zerif-pro/woocommerce-ready/
https://demo.themeisle.com/zblackbeard/
https://demo.themeisle.com/ResponsiveBoat/

This should be the end result: https://www.useloom.com/share/bf174a0f699b4dc19a123f76255f00ca

**Comment by rodica-andronache** [comment]
@dascalescuro I installed the plugin. You just need to go to each individual demo and activate it.
I didn't activate it because as soon as it's activated, the switcher appears and it looks odd without any date included there. So, I think you'd have to fill in the fields as soon as you activate the plugin on each individual demo

**Comment by dascalescuro** [comment]
great! thanks

*Claudiu Dascalescu*
Marketing *@ *ThemeIsle
Mobile: +40740755107
<https://twitter.com/dascalescu>  <https://www.linkedin.com/in/dascalescu>
<https://github.com/Codeinwp/>
